package Pore;

import java.util.*;

public class Pore {

	public String simulatePore(String sequence, Error ErrorModel, LengthDistribution length )
	{
		Random rand = new Random();
		//random number between 0 and sequenceLength-1 is created
		int start = rand.nextInt(sequence.length());
		
		/*
		 *  if the given length is smaller than the difference
		 *  between sequenceLength and start this length can be used
		 *  otherwise it would cause an outOfBounds-Error 
		 */
		while(length > sequence.length()-start)
		{
			//length= LengthDistribution.giveRandomLength;
			
		}
		
		String subseq = sequence.substring(start, start+length);
		
		String fasta = "<html> >sequence generated by MinION-Pore <br>" ;
				
		fasta = fasta + Error.ApplyError(subseq)+"</html>"; //schreibt es einen neuen String?sghs
		
		return fasta;
		
		
	}
	


}
