
package gui;
import java.io.IOException;

import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

import Basecalling.createSetting;
import controller.Controller;
import error.MyException;
import LengthDistribution.LengthDistribution;
import LengthDistribution.LengthRate;

/**
 * @author Sven Bizu
 * -Class creates frame to interact with user. 
 * -Gui gets all userinput and performs sanitychecks.
 * -Userinput:	
 * 	inputFilename:						Receives FastaFile
	outputFilename:						Outfilename for simulation
	writeInFileOption:					Write in File or in Real-Time?
	basecalling:						1D/2D basecalling?
	numberOfPores:						Number of Pores to be simulated
	maxAgeOfPores:						Maximal Age of Pores (time dependant)
	durationOfTick:						How long does one simulation step take
	totalNumberOfTicks:					How long should be simulated.
	windowSizeForLengthDistribution:	Window Size
	basecallingSetup:					Simulate with a given basecalling-probability-file.
	lengthDistributionSetup:			Simulate with a given Length-Distribution-file (not working)
	outputFormat:						Determine Output file (fasta or fastq)
 * -Created with Netbeans Formeditor.
 * 
 */
public class guiFinal extends javax.swing.JFrame {
	
	private Controller cd;

    
    javax.swing.JFileChooser mainFileChooser = new javax.swing.JFileChooser();
    javax.swing.JFileChooser lengthDistributionChooser = new javax.swing.JFileChooser();
    javax.swing.JFileChooser baseCallingChooser = new javax.swing.JFileChooser();
    javax.swing.JFileChooser createBasecallingBlastFileChooser = new javax.swing.JFileChooser();
    javax.swing.JFileChooser createLengthDistributionFastAFileChooser = new javax.swing.JFileChooser();
    javax.swing.JFileChooser settingFileDirectory = new javax.swing.JFileChooser();
    

    /**
     * Creates new form NewJFrame
     */
    public guiFinal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        inputFileTypeGroup = new javax.swing.ButtonGroup();
        optionsDialog = new javax.swing.JDialog();
        optionsTabbedPane = new javax.swing.JTabbedPane();
        inputTab = new javax.swing.JPanel();
        inputFileType = new javax.swing.JPanel();
        fastA = new javax.swing.JRadioButton();
        fastQ = new javax.swing.JRadioButton();
        agingPoresJPanel = new javax.swing.JPanel();
        agingPoresYes = new javax.swing.JRadioButton();
        agingPoresNo = new javax.swing.JRadioButton();
        settingsTab = new javax.swing.JPanel();
        lengthDistributionPanel = new javax.swing.JPanel();
        ldNameLabel = new javax.swing.JLabel();
        ldCreateButton = new javax.swing.JButton();
        ldFastALabel = new javax.swing.JLabel();
        ldBrowseButton = new javax.swing.JButton();
        ldFileNameTextField = new javax.swing.JTextField();
        ldFastATextField = new javax.swing.JTextField();
        basecallingPanel = new javax.swing.JPanel();
        bNameLabel = new javax.swing.JLabel();
        bComboBox = new javax.swing.JComboBox();
        bDimensionLabel = new javax.swing.JLabel();
        bBlastSourceFileLabel = new javax.swing.JLabel();
        bCreateButton = new javax.swing.JButton();
        bNameTextField = new javax.swing.JTextField();
        bBlastPathTextField = new javax.swing.JTextField();
        bBrowseButton = new javax.swing.JButton();
        settingFileDirectoryLabel = new javax.swing.JLabel();
        settingFileDirectoryTextField = new javax.swing.JTextField();
        settingFileDirectoryButton = new javax.swing.JButton();
        agingPoresButtonGroup = new javax.swing.ButtonGroup();
        InputPanel = new javax.swing.JPanel();
        sourceField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        nopLabel = new javax.swing.JLabel();
        totalNumberOfTicksLabel = new javax.swing.JLabel();
        durPerTickLabel = new javax.swing.JLabel();
        dimLabel = new javax.swing.JLabel();
        dimComboBox = new javax.swing.JComboBox();
        windowSizeForLengthDistributionLabel = new javax.swing.JLabel();
        outputFileTextField = new javax.swing.JTextField();
        outputFilenameLabel = new javax.swing.JLabel();
        numberOfTicksTextField = new javax.swing.JFormattedTextField();
        durationPerTickFormattedTextField = new javax.swing.JFormattedTextField();
        windowSizeFormattedTextField = new javax.swing.JFormattedTextField();
        maxAgeOfPoresLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        outputComboBox = new javax.swing.JComboBox();
        mainSettingFilesPanel = new javax.swing.JPanel();
        windowSizeForLengthDistributionLabel1 = new javax.swing.JLabel();
        windowSizeForLengthDistributionLabel2 = new javax.swing.JLabel();
        mainBasecallingSourceTextField = new javax.swing.JTextField();
        mainLdSettingTextField = new javax.swing.JTextField();
        mainBasecallingBrowseButton = new javax.swing.JButton();
        mainLdBrowseButton = new javax.swing.JButton();
        numberOfPoresFormattedTextField = new javax.swing.JFormattedTextField();
        maxAgeOfPoresTextField = new javax.swing.JFormattedTextField();
        runPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        outputPanel = new javax.swing.JPanel();
        outputScrollPane = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadFileMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        toolMenu = new javax.swing.JMenu();
        createSettingFileMenuItem = new javax.swing.JMenuItem();
        settingsMenu = new javax.swing.JMenu();
        InputSettingsMenuItem = new javax.swing.JMenuItem();

        optionsDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        optionsDialog.setMinimumSize(new java.awt.Dimension(620, 430));

        optionsTabbedPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));
        optionsTabbedPane.setMinimumSize(new java.awt.Dimension(117, 151));

        inputFileType.setBorder(javax.swing.BorderFactory.createTitledBorder("Input-File-Type"));

        inputFileTypeGroup.add(fastA);
        fastA.setText("FastA");
        fastA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastAActionPerformed(evt);
            }
        });

        inputFileTypeGroup.add(fastQ);
        fastQ.setText("FastQ");
        fastQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputFileTypeLayout = new javax.swing.GroupLayout(inputFileType);
        inputFileType.setLayout(inputFileTypeLayout);
        inputFileTypeLayout.setHorizontalGroup(
            inputFileTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFileTypeLayout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(fastA)
                .addGap(47, 47, 47)
                .addComponent(fastQ)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        inputFileTypeLayout.setVerticalGroup(
            inputFileTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFileTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputFileTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fastA)
                    .addComponent(fastQ))
                .addGap(11, 11, 11))
        );

        agingPoresJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Aging Pores"));

        agingPoresButtonGroup.add(agingPoresYes);
        agingPoresYes.setSelected(true);
        agingPoresYes.setText("Yes");
        agingPoresYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agingPoresYesActionPerformed(evt);
            }
        });

        agingPoresButtonGroup.add(agingPoresNo);
        agingPoresNo.setText("No");
        agingPoresNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agingPoresNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agingPoresJPanelLayout = new javax.swing.GroupLayout(agingPoresJPanel);
        agingPoresJPanel.setLayout(agingPoresJPanelLayout);
        agingPoresJPanelLayout.setHorizontalGroup(
            agingPoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agingPoresJPanelLayout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(agingPoresYes)
                .addGap(47, 47, 47)
                .addComponent(agingPoresNo)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        agingPoresJPanelLayout.setVerticalGroup(
            agingPoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agingPoresJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agingPoresJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agingPoresYes)
                    .addComponent(agingPoresNo))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout inputTabLayout = new javax.swing.GroupLayout(inputTab);
        inputTab.setLayout(inputTabLayout);
        inputTabLayout.setHorizontalGroup(
            inputTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputFileType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(agingPoresJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        inputTabLayout.setVerticalGroup(
            inputTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputTabLayout.createSequentialGroup()
                .addComponent(inputFileType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agingPoresJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );

        optionsTabbedPane.addTab("Input", inputTab);

        lengthDistributionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Length-Distribution-Error"));

        ldNameLabel.setText("Name of File created:");

        ldCreateButton.setText("Create");
        ldCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldCreateButtonActionPerformed(evt);
            }
        });

        ldFastALabel.setText("FastA-File:");

        ldBrowseButton.setText("Browse..");
        ldBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldBrowseButtonActionPerformed(evt);
            }
        });

        ldFileNameTextField.setText("LengthDistributionErrorFile");

        ldFastATextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldFastATextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lengthDistributionPanelLayout = new javax.swing.GroupLayout(lengthDistributionPanel);
        lengthDistributionPanel.setLayout(lengthDistributionPanelLayout);
        lengthDistributionPanelLayout.setHorizontalGroup(
            lengthDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lengthDistributionPanelLayout.createSequentialGroup()
                .addGroup(lengthDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ldNameLabel)
                    .addComponent(ldFastALabel))
                .addGap(18, 18, 18)
                .addGroup(lengthDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ldFileNameTextField)
                    .addComponent(ldFastATextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ldBrowseButton)
                .addGap(42, 42, 42))
            .addGroup(lengthDistributionPanelLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(ldCreateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lengthDistributionPanelLayout.setVerticalGroup(
            lengthDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lengthDistributionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lengthDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldNameLabel)
                    .addComponent(ldFileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lengthDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldFastALabel)
                    .addComponent(ldBrowseButton)
                    .addComponent(ldFastATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(ldCreateButton))
        );

        basecallingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Basecalling-Error"));

        bNameLabel.setText("Name of File created:");

        bComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1D", "2D" }));

        bDimensionLabel.setText("Dimension:");

        bBlastSourceFileLabel.setText("Blast Sourcefile:");

        bCreateButton.setText("Create");
        bCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCreateButtonActionPerformed(evt);
            }
        });

        bNameTextField.setText("BasecallingErrorFile");
        bNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNameTextFieldActionPerformed(evt);
            }
        });

        bBlastPathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBlastPathTextFieldActionPerformed(evt);
            }
        });

        bBrowseButton.setText("Browse..");
        bBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBrowseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basecallingPanelLayout = new javax.swing.GroupLayout(basecallingPanel);
        basecallingPanel.setLayout(basecallingPanelLayout);
        basecallingPanelLayout.setHorizontalGroup(
            basecallingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basecallingPanelLayout.createSequentialGroup()
                .addGroup(basecallingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bNameLabel)
                    .addComponent(bDimensionLabel)
                    .addComponent(bBlastSourceFileLabel))
                .addGap(18, 18, 18)
                .addGroup(basecallingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basecallingPanelLayout.createSequentialGroup()
                        .addComponent(bBlastPathTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bBrowseButton)
                        .addGap(40, 40, 40))
                    .addGroup(basecallingPanelLayout.createSequentialGroup()
                        .addComponent(bComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(335, 335, 335))
                    .addGroup(basecallingPanelLayout.createSequentialGroup()
                        .addComponent(bNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                        .addGap(125, 125, 125))))
            .addGroup(basecallingPanelLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(bCreateButton)
                .addContainerGap())
        );
        basecallingPanelLayout.setVerticalGroup(
            basecallingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basecallingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basecallingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNameLabel)
                    .addComponent(bNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basecallingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDimensionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basecallingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBlastSourceFileLabel)
                    .addComponent(bBlastPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCreateButton))
        );

        settingFileDirectoryLabel.setText("Setting-File-Directory:");

        settingFileDirectoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingFileDirectoryTextFieldActionPerformed(evt);
            }
        });

        settingFileDirectoryButton.setText("Browse..");
        settingFileDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingFileDirectoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsTabLayout = new javax.swing.GroupLayout(settingsTab);
        settingsTab.setLayout(settingsTabLayout);
        settingsTabLayout.setHorizontalGroup(
            settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lengthDistributionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(basecallingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(settingsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingFileDirectoryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingFileDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(settingFileDirectoryButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        settingsTabLayout.setVerticalGroup(
            settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingFileDirectoryLabel)
                    .addComponent(settingFileDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingFileDirectoryButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lengthDistributionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basecallingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        optionsTabbedPane.addTab("Create Setting Files", settingsTab);

        javax.swing.GroupLayout optionsDialogLayout = new javax.swing.GroupLayout(optionsDialog.getContentPane());
        optionsDialog.getContentPane().setLayout(optionsDialogLayout);
        optionsDialogLayout.setHorizontalGroup(
            optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(optionsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        optionsDialogLayout.setVerticalGroup(
            optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(optionsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));

        sourceField.setText("..\\desktop\\example.fasta");

        browseButton.setText("Browse..");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        nopLabel.setText("Number of pores:");

        totalNumberOfTicksLabel.setText("Total number of ticks:");

        durPerTickLabel.setText("Duration per tick in s:");

        dimLabel.setText("Dimension:");

        dimComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1D", "2D" }));

        windowSizeForLengthDistributionLabel.setText("Window size:");

        outputFileTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFileTextFieldActionPerformed(evt);
            }
        });

        outputFilenameLabel.setText("Outputfile-name:");

        numberOfTicksTextField.setText("1000");
        numberOfTicksTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfTicksTextFieldActionPerformed(evt);
            }
        });

        durationPerTickFormattedTextField.setText("1");
        durationPerTickFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationPerTickFormattedTextFieldActionPerformed(evt);
            }
        });

        windowSizeFormattedTextField.setText("1000");

        maxAgeOfPoresLabel.setText("Maximal Age of pores:");

        outputLabel.setText("Output:");

        outputComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Real-Time", "Write all" }));
        outputComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputComboBoxActionPerformed(evt);
            }
        });

        mainSettingFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Setting-Files"));

        windowSizeForLengthDistributionLabel1.setText("Basecalling-Error-Setting-File:");

        windowSizeForLengthDistributionLabel2.setText("Length-Distribution-Setting-File:");

        mainBasecallingSourceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBasecallingSourceTextFieldActionPerformed(evt);
            }
        });

        mainLdSettingTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainLdSettingTextFieldActionPerformed(evt);
            }
        });

        mainBasecallingBrowseButton.setText("Browse..");
        mainBasecallingBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBasecallingBrowseButtonActionPerformed(evt);
            }
        });

        mainLdBrowseButton.setText("Browse..");
        mainLdBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainLdBrowseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainSettingFilesPanelLayout = new javax.swing.GroupLayout(mainSettingFilesPanel);
        mainSettingFilesPanel.setLayout(mainSettingFilesPanelLayout);
        mainSettingFilesPanelLayout.setHorizontalGroup(
            mainSettingFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSettingFilesPanelLayout.createSequentialGroup()
                .addGroup(mainSettingFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainSettingFilesPanelLayout.createSequentialGroup()
                        .addComponent(windowSizeForLengthDistributionLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(mainBasecallingSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mainBasecallingBrowseButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainSettingFilesPanelLayout.createSequentialGroup()
                        .addComponent(windowSizeForLengthDistributionLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainLdSettingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mainLdBrowseButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainSettingFilesPanelLayout.setVerticalGroup(
            mainSettingFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSettingFilesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainSettingFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(windowSizeForLengthDistributionLabel1)
                    .addComponent(mainBasecallingSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainBasecallingBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSettingFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(windowSizeForLengthDistributionLabel2)
                    .addComponent(mainLdSettingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainLdBrowseButton)))
        );

        numberOfPoresFormattedTextField.setText("5");
        numberOfPoresFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfPoresFormattedTextFieldActionPerformed(evt);
            }
        });

        maxAgeOfPoresTextField.setText("1000");
        maxAgeOfPoresTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxAgeOfPoresTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxAgeOfPoresLabel)
                    .addComponent(totalNumberOfTicksLabel)
                    .addComponent(durPerTickLabel)
                    .addComponent(dimLabel)
                    .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nopLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sourceField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(7, 7, 7)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(browseButton)
                            .addComponent(numberOfTicksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(durationPerTickFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dimComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(mainSettingFilesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxAgeOfPoresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOfPoresFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(windowSizeForLengthDistributionLabel)
                            .addComponent(outputFilenameLabel)
                            .addComponent(outputLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(outputFileTextField)
                            .addComponent(outputComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(windowSizeFormattedTextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton)
                    .addComponent(outputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputFilenameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nopLabel)
                    .addComponent(outputLabel)
                    .addComponent(outputComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfPoresFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maxAgeOfPoresLabel)
                        .addComponent(maxAgeOfPoresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(windowSizeForLengthDistributionLabel)
                        .addComponent(windowSizeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainSettingFilesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOfTicksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalNumberOfTicksLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(durPerTickLabel)
                            .addComponent(durationPerTickFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dimComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dimLabel)))))
        );

        runPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Run"));

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.setEnabled(false);
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        pauseButton.setText("Pause");
        pauseButton.setEnabled(false);
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout runPanelLayout = new javax.swing.GroupLayout(runPanel);
        runPanel.setLayout(runPanelLayout);
        runPanelLayout.setHorizontalGroup(
            runPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(runPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pauseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        runPanelLayout.setVerticalGroup(
            runPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(runPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(runPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopButton)
                    .addComponent(pauseButton)
                    .addComponent(startButton))
                .addContainerGap())
        );

        outputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        outputTextArea.setEditable(false);
        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        outputScrollPane.setViewportView(outputTextArea);

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outputScrollPane)
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(outputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        fileMenu.setText("File");

        loadFileMenuItem.setLabel("Load File");
        loadFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadFileMenuItem);

        exitMenuItem.setLabel("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        toolMenu.setText("Tools");

        createSettingFileMenuItem.setText("Create Settingfile");
        createSettingFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSettingFileMenuItemActionPerformed(evt);
            }
        });
        toolMenu.add(createSettingFileMenuItem);

        menuBar.add(toolMenu);

        settingsMenu.setText("Settings");

        InputSettingsMenuItem.setLabel("Input Settings");
        InputSettingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputSettingsMenuItemActionPerformed(evt);
            }
        });
        settingsMenu.add(InputSettingsMenuItem);

        menuBar.add(settingsMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(runPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(runPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>                        

    /*@author Sven Bizu and Friederike Hanssen
     *@functionality Starts Simulation when sanitychecks were passed.
     *@input All inputs by Textfields, Comboboxes and Radiobuttons
     */
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            

        if(checkInput(numberOfPoresFormattedTextField.getText(),maxAgeOfPoresTextField.getText(),numberOfTicksTextField.getText(),durationPerTickFormattedTextField.getText(),
                windowSizeFormattedTextField.getText())){
        	
    	startButton.setEnabled(false);
    	pauseButton.setEnabled(true);
    	stopButton.setEnabled(true);
    	String message= "";
    	int basecalling = 0;
    	String inputFormat = ".fasta";
    		
    	//Check which Input format is chosen
    	if(fastA.isSelected()){
    	   inputFormat=".fasta";
    	    }
    	    else if(fastQ.isSelected()){
    	        inputFormat=".fastq";
    	    }

    	    //Check which dimension for basecalling is chosen
    		String chosen = (String) dimComboBox.getSelectedItem();

    				if (chosen.equals("1D")) {
    					//TODO
    					basecalling =1;
    				} else if (chosen.equals("2D")) {
    				//TODO
    					basecalling=2;
    					}
    				/* Tests for guiFinal Input
    				System.out.println("Number of Pores: "+ Integer.parseInt(numberOfPoresFormattedTextField.getText()));
    				System.out.println("Duration per Tick: "+ Integer.parseInt(durationPerTickFormattedTextField.getText()));
    				System.out.println("Number of Ticks: "+Integer.parseInt(numberOfTicksTextField.getText()));
    				System.out.println("Window Size: "+Integer.parseInt(windowSizeFormattedTextField.getText()));
    				System.out.println("Basecalling: "+basecalling);
    				System.out.println("Basecalling: "+basecalling);
    				System.out.println("Input directory: "+sourceField.getText());
    				System.out.println("Output: "+outputFileTextField.getText());
    			*/
    				/* 	
    				private String inputFilename;
    				private String outputFilename;
    				private String writeInFileOption;
    				private int basecalling;
    				private int numberOfPores;
    				private int maxAgeOfPores;
    				private int durationOfTick;
    				private int totalNumberOfTicks;
    				private int windowSizeForLengthDistribution*/
    				
    				
    			//Class GUIOptions contains all Input Parameters.	
    			GUIOptions options = new GUIOptions(
    					sourceField.getText(),
    					outputFileTextField.getText(), 
    					(String) outputComboBox.getSelectedItem(),
    					inputFormat,"default.setting",
    					basecalling, 
    					Integer.parseInt(numberOfPoresFormattedTextField.getText()),
    					Integer.parseInt(maxAgeOfPoresTextField.getText()),
    					Integer.parseInt(durationPerTickFormattedTextField.getText()),
    					Integer.parseInt(numberOfTicksTextField.getText()),
    					Integer.parseInt(windowSizeFormattedTextField.getText()));
    			this.cd = new Controller(options);
    			
    			//System.out.println(options.getInputFilename());
    			
    			//sanity check by Friederike
    			if(options.hasValidParameters()){
    				try {
    					cd.startController();
    				} catch (MyException e) {
    					e.printStackTrace();
    				}
    			}else{
    				System.err.println("Please enter valid parameters.");
    			}
    				

    		int length= cd.getOutputFileErrors().size();

    		//Creating output for Outputtextfield (not working as intended)
    		
    		for(int i=0; i<length;i++)
    		{
    			if(this.cd.getOutputFileErrors().get(i).isCriticalError()) {
    				JOptionPane.showMessageDialog(null, this.cd.getOutputFileErrors().get(i).getErrorMessage(), "Critical Error", JOptionPane.ERROR_MESSAGE);
    			} else {
    				message= message + " " + this.cd.getOutputFileErrors().get(i).getErrorMessage()+"\n";
    				outputTextArea.setText(message); 
    			}
    		}
        }

    		/*testing the outputTextFieldArea
    		for(int i=0; i<100; i++){
    			message=message+"Test-Line "+i+"\n";
    		}

    		outputTextArea.setText(message);  */
    }                                           
    

    /*
    *@author Friederike; Sven Bizu
    *@functionality pauses Simulation and provides ability to resume simulation
    */                                          

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        
    	
    	//If Simulation is paused rename label "Pause" to "Resume"
    	if(pauseButton.getText()=="Pause"){
	    	stopButton.setEnabled(false);
	    	pauseButton.setText("Resume");
	        try {
				cd.pause();
			} catch (MyException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	    }
    	//If Simulation is resumed rename label "Resume" to "Pause"
	    else{
	    	stopButton.setEnabled(true);
	    	pauseButton.setText("Pause");
	    	
	    	try {
				cd.resume();
			} catch (MyException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}  
	    	
	    }
		
    	}                                         
                                               
    /*
    *@author Sven Bizu
    *@functionality close Programm when clicking on Exit in menubar
    */  
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                             
    System.exit(0);
    }                                            
    
    /*
    *@author Sven Bizu
    *@functionality browse to set directory for LengthDistribution in Mainframe (unused)
    */
    private void mainLdBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
   	 lengthDistributionChooser.showOpenDialog(guiFinal.this);
   	 mainLdSettingTextField.setText(lengthDistributionChooser.getSelectedFile().getAbsolutePath());
    }                                                  

    /*
    *@author Sven Bizu
    *@functionality browse to set directory for Basecalling (unused)
    */
    private void mainBasecallingBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                            
    baseCallingChooser.showOpenDialog(guiFinal.this);
    mainBasecallingSourceTextField.setText(baseCallingChooser.getSelectedFile().getAbsolutePath());
    }
    

    private void mainLdSettingTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void mainBasecallingSourceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        // TODO add your handling code here:
    }                                                              

    private void durationPerTickFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                                  
        // TODO add your handling code here:
    }                                                                 

    private void outputFileTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                    

    }                                                   

    /*
    *@author Sven Bizu
    *@functionality browse to set directory for FastA/FastQ file
    */
    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
   	 mainFileChooser.showOpenDialog(guiFinal.this);
     sourceField.setText(mainFileChooser.getSelectedFile().getAbsolutePath());
     // Default settingfilepath is set by importing the fastA/fastQ file
     if(settingFileDirectoryTextField.getText().isEmpty()){
     	int sep = mainFileChooser.getSelectedFile().getAbsolutePath().lastIndexOf("\\");
     	settingFileDirectoryTextField.setText(mainFileChooser.getSelectedFile().getAbsolutePath().substring(0, sep));	
     }
     // Default Output-Filename is set: inputFilename_result.TXT
     if(outputFileTextField.getText().isEmpty()){
     	int dot = mainFileChooser.getSelectedFile().getAbsolutePath().lastIndexOf(".");
         int sep = mainFileChooser.getSelectedFile().getAbsolutePath().lastIndexOf("\\");
         String out = mainFileChooser.getSelectedFile().getAbsolutePath().substring(sep + 1, dot);
         out=out+"_result.TXT";
         outputFileTextField.setText(out);
     }
    }                                            

    /*
    *@author Sven Bizu
    *@functionality browse to set directory for SettingFiles (Basecalling and LengthDistribution
    */
    private void settingFileDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                           
    	settingFileDirectory.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        settingFileDirectory.showOpenDialog(guiFinal.this);
        settingFileDirectoryTextField.setText(settingFileDirectory.getSelectedFile().getAbsolutePath());
    }                                                          

    private void settingFileDirectoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
    }                                                             

    /*
    *@author Sven Bizu
    *@functionality choose Basecalling-File for simulation run (not used)
    */
    private void bBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	createBasecallingBlastFileChooser.showOpenDialog(guiFinal.this);
        bBlastPathTextField.setText(createBasecallingBlastFileChooser.getSelectedFile().getAbsolutePath());
    }                                             

    private void bBlastPathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void bNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void ldFastATextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    /*
    *@author Sven Bizu
    *@functionality select Length-Distribution-File for simulation (not used)
    */
    private void ldBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
   	 createLengthDistributionFastAFileChooser.showOpenDialog(guiFinal.this);
     ldFastATextField.setText(createLengthDistributionFastAFileChooser.getSelectedFile().getAbsolutePath());
    }                                              

    private void fastQActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void fastAActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void outputComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    /*
    *@author Sven Bizu
    *@functionality open tabbedpane in settingfile-tab
    */
    private void createSettingFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        optionsTabbedPane.setSelectedIndex(1);
        optionsDialog.setVisible(true);
    }                                                         

    private void loadFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    /*
    *@author Sven Bizu
    *@functionality open tabbed-pane in input-tab
    */
    private void InputSettingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        optionsTabbedPane.setSelectedIndex(0);
        optionsDialog.setVisible(true);
    }                                                     

    /*
    *@author Friederike and Sven Bizu 
    *@functionality Stop Simulation and reset Buttons to original state
    */
    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        pauseButton.setText("Pause");
        pauseButton.setEnabled(false);
        stopButton.setEnabled(false);
        startButton.setEnabled(true);
        String message ="";
        try {
    		cd.stop();
    	} catch (MyException e) {
    		e.printStackTrace();
    	}
        int length= cd.getOutputFileErrors().size();
        System.out.println(cd.getOutputFileErrors().size());
    	for(int i=0; i<length;i++)
		{
			if(this.cd.getOutputFileErrors().get(i).isCriticalError()) {
				JOptionPane.showMessageDialog(null, this.cd.getOutputFileErrors().get(i).getErrorMessage(), "Critical Error", JOptionPane.ERROR_MESSAGE);
			} else {
				message= message + " " + this.cd.getOutputFileErrors().get(i).getErrorMessage()+"\n";
				outputTextArea.setText(message); 
			}
		}
    }                                              

    /*
    *@author Sven Bizu
    *@functionality create Length Distribution by reading a FastA-File and Name for File to be created (not working)
    */
    private void ldCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	
    int ws=Integer.parseInt(windowSizeFormattedTextField.getText());
    try{
    	LengthDistribution ld = new LengthDistribution(ldFastATextField.getText(),ws);
    	ld.getRate().saveSelectedLengths(ldFastATextField.getText(), ldFileNameTextField.getText());
    }catch (IOException e){
    	e.printStackTrace();
    }
    
    	
    }                                              

    /*
    *@author Sven Bizu and Kevin
    *@functionality create basecalling-settingfile by Blast-file
    */
    private void bCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
    	try {
			createSetting.createSettingFile(bBlastPathTextField.getText(),settingFileDirectoryTextField.getText()+"\\"+bNameTextField.getText(),bComboBox.getSelectedIndex()+1);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }                                             

    private void numberOfTicksTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void agingPoresYesActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void agingPoresNoActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void numberOfPoresFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                                
        // TODO add your handling code here:
    }                                                               

    private void maxAgeOfPoresTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

 
    // Variables declaration - do not modify                     
    private javax.swing.JPanel InputPanel;
    private javax.swing.JMenuItem InputSettingsMenuItem;
    private javax.swing.ButtonGroup agingPoresButtonGroup;
    private javax.swing.JPanel agingPoresJPanel;
    private javax.swing.JRadioButton agingPoresNo;
    private javax.swing.JRadioButton agingPoresYes;
    private javax.swing.JTextField bBlastPathTextField;
    private javax.swing.JLabel bBlastSourceFileLabel;
    private javax.swing.JButton bBrowseButton;
    private javax.swing.JComboBox bComboBox;
    private javax.swing.JButton bCreateButton;
    private javax.swing.JLabel bDimensionLabel;
    private javax.swing.JLabel bNameLabel;
    private javax.swing.JTextField bNameTextField;
    private javax.swing.JPanel basecallingPanel;
    private javax.swing.JButton browseButton;
    private javax.swing.JMenuItem createSettingFileMenuItem;
    private javax.swing.JComboBox dimComboBox;
    private javax.swing.JLabel dimLabel;
    private javax.swing.JLabel durPerTickLabel;
    private javax.swing.JFormattedTextField durationPerTickFormattedTextField;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JRadioButton fastA;
    private javax.swing.JRadioButton fastQ;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel inputFileType;
    private javax.swing.ButtonGroup inputFileTypeGroup;
    private javax.swing.JPanel inputTab;
    private javax.swing.JButton ldBrowseButton;
    private javax.swing.JButton ldCreateButton;
    private javax.swing.JLabel ldFastALabel;
    private javax.swing.JTextField ldFastATextField;
    private javax.swing.JTextField ldFileNameTextField;
    private javax.swing.JLabel ldNameLabel;
    private javax.swing.JPanel lengthDistributionPanel;
    private javax.swing.JMenuItem loadFileMenuItem;
    private javax.swing.JButton mainBasecallingBrowseButton;
    private javax.swing.JTextField mainBasecallingSourceTextField;
    private javax.swing.JButton mainLdBrowseButton;
    private javax.swing.JTextField mainLdSettingTextField;
    private javax.swing.JPanel mainSettingFilesPanel;
    private javax.swing.JLabel maxAgeOfPoresLabel;
    private javax.swing.JFormattedTextField maxAgeOfPoresTextField;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nopLabel;
    private javax.swing.JFormattedTextField numberOfPoresFormattedTextField;
    private javax.swing.JFormattedTextField numberOfTicksTextField;
    private javax.swing.JDialog optionsDialog;
    private javax.swing.JTabbedPane optionsTabbedPane;
    private javax.swing.JComboBox outputComboBox;
    private javax.swing.JTextField outputFileTextField;
    private javax.swing.JLabel outputFilenameLabel;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JScrollPane outputScrollPane;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JButton pauseButton;
    private javax.swing.JPanel runPanel;
    private javax.swing.JButton settingFileDirectoryButton;
    private javax.swing.JLabel settingFileDirectoryLabel;
    private javax.swing.JTextField settingFileDirectoryTextField;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JPanel settingsTab;
    private javax.swing.JTextField sourceField;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JMenu toolMenu;
    private javax.swing.JLabel totalNumberOfTicksLabel;
    private javax.swing.JLabel windowSizeForLengthDistributionLabel;
    private javax.swing.JLabel windowSizeForLengthDistributionLabel1;
    private javax.swing.JLabel windowSizeForLengthDistributionLabel2;
    private javax.swing.JFormattedTextField windowSizeFormattedTextField;
    // End of variables declaration                   

    /*
    *@author Sven Bizu
    *@functionality check each textfield (not Directories!). Pop up if input is NaN or not a valid number.
    *@output boolean
    */
    
    public static boolean checkNumOfPores(String num){
        try {
            Integer.parseInt(num);
            }
        catch(NumberFormatException e) {
          JOptionPane.showMessageDialog(null,"Number of Pores is not a number.","Wrong Input",JOptionPane.WARNING_MESSAGE);
        return false;
            }
        if(Integer.parseInt(num)>0){
            return true;
        }else{
            JOptionPane.showMessageDialog(null,"Number of Pores can't be negative.","Wrong Input",JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }
    
        public static boolean checkTicks(String num){
        try {
            Integer.parseInt(num);
            }
        catch(NumberFormatException e) {
          JOptionPane.showMessageDialog(null,"Number of Ticks is not a number.","Wrong Input",JOptionPane.WARNING_MESSAGE);
        return false;
            }
        if(Integer.parseInt(num)>0){
            return true;
        }else{
            JOptionPane.showMessageDialog(null,"Number of Ticks can't be negative.","Wrong Input",JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }
        public static boolean checkAge(String num){
        try {
            Integer.parseInt(num);
            }
        catch(NumberFormatException e) {
          JOptionPane.showMessageDialog(null,"Maximal Age is not a number","Wrong Input",JOptionPane.WARNING_MESSAGE);
        return false;
            }
        if(Integer.parseInt(num)>0){
            return true;
        }else{
            JOptionPane.showMessageDialog(null,"Maximal Age can't be negative","Wrong Input",JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }
    public static boolean checkDuration(String num){
        try {
            Integer.parseInt(num);
            }
        catch(NumberFormatException e) {
          JOptionPane.showMessageDialog(null,"Duration per Tick is not a number","Wrong Input",JOptionPane.WARNING_MESSAGE);
        return false;
            }
        if(Integer.parseInt(num)>0){
            return true;
        }else{
            JOptionPane.showMessageDialog(null,"Duration per Tick can't be negative","Wrong Input",JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }
    
    public static boolean checkWindowSize(String num){
        try {
            Integer.parseInt(num);
            }
        catch(NumberFormatException e) {
          JOptionPane.showMessageDialog(null,"Window Size is not a number","Wrong Input",JOptionPane.WARNING_MESSAGE);
        return false;
            }
        if(Integer.parseInt(num)>0){
            return true;
        }else{
            JOptionPane.showMessageDialog(null,"Window Size can't be negative","Wrong Input",JOptionPane.WARNING_MESSAGE);
            return false;
        }
    }
    
    /*
    *@author Sven Bizu
    *@functionality use all sanity check functions
    *@output boolean
    */
    
    public static boolean checkInput(String numOfPores, String age, String numTicks, String duration, String windowSize){
        
        
        if(checkNumOfPores(numOfPores) && checkAge(age) && checkTicks(numTicks) && checkDuration(duration) && checkWindowSize(windowSize)){
            return true;
        }else  
            return false;
        
    }
    
    public static void main(String[] args) throws MyException {
        guiFinal sim = new guiFinal();
        sim.setVisible(true);
//        sim.statistics();
    }

    
    /**
     * @author Daniel
     * @throws MyException
     * @function computes a new guiFinalstatistics object. 
     */
 /* public void statistics() throws MyException
  { 	//TODO reads need to be implemented
  	//gets a double array with the values (number of Reads), Quality, dead pores, running pores, sleeping pores, alive pores, bored pores usw.
  	//[0] Running, [1]Bored, [2] Dead,[3] Finished, [4] Sleeping,[5] sum of Pores
	double reads = 10;
	double[] porestates =  cd.getFlowcell().getStates(); 
  	guiFinalStatistics chart = new guiFinalStatistics(porestates,reads);
	chart.pack();
	chart.setVisible(true);

	//adds new data everytime the update function is called.
	chart.updateData(porestates, reads);
  	
	      
	     
  }*/ 


}

