
package gui;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

import controller.Controller;

/**
 * @author Sven
 */
public class minION extends javax.swing.JFrame {
    
    javax.swing.JFileChooser mainFileChooser = new javax.swing.JFileChooser();
    javax.swing.JFileChooser lengthDistributionChooser = new javax.swing.JFileChooser();
    javax.swing.JFileChooser baseCallingChooser = new javax.swing.JFileChooser();
    javax.swing.JFileChooser createBasecallingBlastFileChooser = new javax.swing.JFileChooser();
    javax.swing.JFileChooser createLengthDistributionFastAFileChooser = new javax.swing.JFileChooser();
    javax.swing.JFileChooser settingFileDirectory = new javax.swing.JFileChooser();
    
    	private String inputFilename;
	private String outputFilename;
	private int basecalling;
	private int ticksPerSecond;
	private int numberOfPores;
	private int runningTime;
	private int windowSizeForLengthDistribution;
    /**
     * Creates new form NewJFrame
     */
    public minION() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        inputFileTypeGroup = new javax.swing.ButtonGroup();
        outputGroup = new javax.swing.ButtonGroup();
        optionsDialog = new javax.swing.JDialog();
        optionsTabbedPane = new javax.swing.JTabbedPane();
        inputTab = new javax.swing.JPanel();
        inputFileType = new javax.swing.JPanel();
        fastA = new javax.swing.JRadioButton();
        fastQ = new javax.swing.JRadioButton();
        settingsTab = new javax.swing.JPanel();
        lengthDistributionPanel = new javax.swing.JPanel();
        ldNameLabel = new javax.swing.JLabel();
        ldCreateButton = new javax.swing.JButton();
        ldFastALabel = new javax.swing.JLabel();
        ldBrowseButton = new javax.swing.JButton();
        ldFileNameTextField = new javax.swing.JTextField();
        ldFastATextField = new javax.swing.JTextField();
        basecallingPanel = new javax.swing.JPanel();
        bNameLabel = new javax.swing.JLabel();
        bComboBox = new javax.swing.JComboBox();
        bDimensionLabel = new javax.swing.JLabel();
        bBlastSourceFileLabel = new javax.swing.JLabel();
        bCreateButton = new javax.swing.JButton();
        bNameTextField = new javax.swing.JTextField();
        bBlastPathTextField = new javax.swing.JTextField();
        bBrowseButton = new javax.swing.JButton();
        settingFileDirectoryLabel = new javax.swing.JLabel();
        settingFileDirectoryTextField = new javax.swing.JTextField();
        settingFileDirectoryButton = new javax.swing.JButton();
        InputPanel = new javax.swing.JPanel();
        sourceField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        nopLabel = new javax.swing.JLabel();
        totalNumberOfTicksLabel = new javax.swing.JLabel();
        durPerTickLabel = new javax.swing.JLabel();
        dimLabel = new javax.swing.JLabel();
        dimComboBox = new javax.swing.JComboBox();
        windowSizeForLengthDistributionLabel = new javax.swing.JLabel();
        outputFileTextField = new javax.swing.JTextField();
        outputFilenameLabel = new javax.swing.JLabel();
        maxAgeOfPoresTextField = new javax.swing.JFormattedTextField();
        numberOfTicksTextField = new javax.swing.JFormattedTextField();
        durationPerTickFormattedTextField = new javax.swing.JFormattedTextField();
        windowSizeFormattedTextField = new javax.swing.JFormattedTextField();
        maxAgeOfPoresLabel = new javax.swing.JLabel();
        numberOfPoresFormattedTextField1 = new javax.swing.JFormattedTextField();
        outputLabel = new javax.swing.JLabel();
        outputComboBox = new javax.swing.JComboBox();
        mainSettingFilesPanel = new javax.swing.JPanel();
        windowSizeForLengthDistributionLabel1 = new javax.swing.JLabel();
        windowSizeForLengthDistributionLabel2 = new javax.swing.JLabel();
        mainBasecallingSourceTextField = new javax.swing.JTextField();
        mainLdSettingTextField = new javax.swing.JTextField();
        mainBasecallingBrowseButton = new javax.swing.JButton();
        mainLdBrowseButton = new javax.swing.JButton();
        runPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        pauseButton = new javax.swing.JButton();
        outputPanel = new javax.swing.JPanel();
        outputScrollPane = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadFileMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        toolMenu = new javax.swing.JMenu();
        createSettingFileMenuItem = new javax.swing.JMenuItem();
        settingsMenu = new javax.swing.JMenu();
        InputSettingsMenuItem = new javax.swing.JMenuItem();

        optionsDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        optionsDialog.setMinimumSize(new java.awt.Dimension(620, 430));

        optionsTabbedPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));
        optionsTabbedPane.setMinimumSize(new java.awt.Dimension(117, 151));

        inputFileType.setBorder(javax.swing.BorderFactory.createTitledBorder("Input-File-Type"));

        inputFileTypeGroup.add(fastA);
        fastA.setSelected(true);
        fastA.setText("FastA");
        fastA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastAActionPerformed(evt);
            }
        });

        inputFileTypeGroup.add(fastQ);
        fastQ.setText("FastQ");
        fastQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputFileTypeLayout = new javax.swing.GroupLayout(inputFileType);
        inputFileType.setLayout(inputFileTypeLayout);
        inputFileTypeLayout.setHorizontalGroup(
            inputFileTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFileTypeLayout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(fastA)
                .addGap(47, 47, 47)
                .addComponent(fastQ)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        inputFileTypeLayout.setVerticalGroup(
            inputFileTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputFileTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputFileTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fastA)
                    .addComponent(fastQ))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout inputTabLayout = new javax.swing.GroupLayout(inputTab);
        inputTab.setLayout(inputTabLayout);
        inputTabLayout.setHorizontalGroup(
            inputTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inputFileType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        inputTabLayout.setVerticalGroup(
            inputTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputTabLayout.createSequentialGroup()
                .addComponent(inputFileType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );

        optionsTabbedPane.addTab("Input", inputTab);

        lengthDistributionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Length-Distribution-Error"));

        ldNameLabel.setText("Name of File created:");

        ldCreateButton.setText("Create");

        ldFastALabel.setText("FastA-File:");

        ldBrowseButton.setText("Browse..");
        ldBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldBrowseButtonActionPerformed(evt);
            }
        });

        ldFileNameTextField.setText("LengthDistributionErrorFile");

        ldFastATextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldFastATextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lengthDistributionPanelLayout = new javax.swing.GroupLayout(lengthDistributionPanel);
        lengthDistributionPanel.setLayout(lengthDistributionPanelLayout);
        lengthDistributionPanelLayout.setHorizontalGroup(
            lengthDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lengthDistributionPanelLayout.createSequentialGroup()
                .addGroup(lengthDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ldNameLabel)
                    .addComponent(ldFastALabel))
                .addGap(18, 18, 18)
                .addGroup(lengthDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ldFileNameTextField)
                    .addComponent(ldFastATextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ldBrowseButton)
                .addGap(42, 42, 42))
            .addGroup(lengthDistributionPanelLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(ldCreateButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lengthDistributionPanelLayout.setVerticalGroup(
            lengthDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lengthDistributionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lengthDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldNameLabel)
                    .addComponent(ldFileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lengthDistributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ldFastALabel)
                    .addComponent(ldBrowseButton)
                    .addComponent(ldFastATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(ldCreateButton))
        );

        basecallingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Basecalling-Error"));

        bNameLabel.setText("Name of File created:");

        bComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1D", "2D" }));

        bDimensionLabel.setText("Dimension:");

        bBlastSourceFileLabel.setText("Blast Sourcefile:");

        bCreateButton.setText("Create");

        bNameTextField.setText("BasecallingErrorFile");
        bNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNameTextFieldActionPerformed(evt);
            }
        });

        bBlastPathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBlastPathTextFieldActionPerformed(evt);
            }
        });

        bBrowseButton.setText("Browse..");
        bBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBrowseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basecallingPanelLayout = new javax.swing.GroupLayout(basecallingPanel);
        basecallingPanel.setLayout(basecallingPanelLayout);
        basecallingPanelLayout.setHorizontalGroup(
            basecallingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basecallingPanelLayout.createSequentialGroup()
                .addGroup(basecallingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bNameLabel)
                    .addComponent(bDimensionLabel)
                    .addComponent(bBlastSourceFileLabel))
                .addGap(18, 18, 18)
                .addGroup(basecallingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basecallingPanelLayout.createSequentialGroup()
                        .addComponent(bBlastPathTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bBrowseButton)
                        .addGap(40, 40, 40))
                    .addGroup(basecallingPanelLayout.createSequentialGroup()
                        .addComponent(bComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(335, 335, 335))
                    .addGroup(basecallingPanelLayout.createSequentialGroup()
                        .addComponent(bNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                        .addGap(125, 125, 125))))
            .addGroup(basecallingPanelLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(bCreateButton)
                .addContainerGap())
        );
        basecallingPanelLayout.setVerticalGroup(
            basecallingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basecallingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basecallingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNameLabel)
                    .addComponent(bNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basecallingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDimensionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basecallingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBlastSourceFileLabel)
                    .addComponent(bBlastPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCreateButton))
        );

        settingFileDirectoryLabel.setText("Setting-File-Directory:");

        settingFileDirectoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingFileDirectoryTextFieldActionPerformed(evt);
            }
        });

        settingFileDirectoryButton.setText("Browse..");
        settingFileDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingFileDirectoryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsTabLayout = new javax.swing.GroupLayout(settingsTab);
        settingsTab.setLayout(settingsTabLayout);
        settingsTabLayout.setHorizontalGroup(
            settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lengthDistributionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(basecallingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(settingsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(settingFileDirectoryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settingFileDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(settingFileDirectoryButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        settingsTabLayout.setVerticalGroup(
            settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(settingFileDirectoryLabel)
                    .addComponent(settingFileDirectoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingFileDirectoryButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lengthDistributionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(basecallingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        optionsTabbedPane.addTab("Create Setting Files", settingsTab);

        javax.swing.GroupLayout optionsDialogLayout = new javax.swing.GroupLayout(optionsDialog.getContentPane());
        optionsDialog.getContentPane().setLayout(optionsDialogLayout);
        optionsDialogLayout.setHorizontalGroup(
            optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(optionsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        optionsDialogLayout.setVerticalGroup(
            optionsDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsDialogLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(optionsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Input"));

        sourceField.setText("..\\desktop\\example.fasta");

        browseButton.setText("Browse..");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        nopLabel.setText("Number of pores:");

        totalNumberOfTicksLabel.setText("Total number of ticks:");

        durPerTickLabel.setText("Duration per tick:");

        dimLabel.setText("Dimension:");

        dimComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1D", "2D" }));

        windowSizeForLengthDistributionLabel.setText("Window size:");

        outputFileTextField.setText("Result");
        outputFileTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFileTextFieldActionPerformed(evt);
            }
        });

        outputFilenameLabel.setText("Outputfile-name:");

        maxAgeOfPoresTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        maxAgeOfPoresTextField.setText("100");
        maxAgeOfPoresTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxAgeOfPoresTextFieldActionPerformed(evt);
            }
        });

        numberOfTicksTextField.setText("5");

        durationPerTickFormattedTextField.setText("1");
        durationPerTickFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationPerTickFormattedTextFieldActionPerformed(evt);
            }
        });

        windowSizeFormattedTextField.setText("1000");

        maxAgeOfPoresLabel.setText("Maximal Age of pores:");

        numberOfPoresFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        numberOfPoresFormattedTextField1.setText("5");
        numberOfPoresFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfPoresFormattedTextField1ActionPerformed(evt);
            }
        });

        outputLabel.setText("Output:");

        outputComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Real-Time", "Write all" }));
        outputComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputComboBoxActionPerformed(evt);
            }
        });

        mainSettingFilesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Setting-Files"));

        windowSizeForLengthDistributionLabel1.setText("Basecalling-Error-Setting-File:");

        windowSizeForLengthDistributionLabel2.setText("Length-Distribution-Setting-File:");

        mainBasecallingSourceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBasecallingSourceTextFieldActionPerformed(evt);
            }
        });

        mainLdSettingTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainLdSettingTextFieldActionPerformed(evt);
            }
        });

        mainBasecallingBrowseButton.setText("Browse..");
        mainBasecallingBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBasecallingBrowseButtonActionPerformed(evt);
            }
        });

        mainLdBrowseButton.setText("Browse..");
        mainLdBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainLdBrowseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainSettingFilesPanelLayout = new javax.swing.GroupLayout(mainSettingFilesPanel);
        mainSettingFilesPanel.setLayout(mainSettingFilesPanelLayout);
        mainSettingFilesPanelLayout.setHorizontalGroup(
            mainSettingFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSettingFilesPanelLayout.createSequentialGroup()
                .addGroup(mainSettingFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainSettingFilesPanelLayout.createSequentialGroup()
                        .addComponent(windowSizeForLengthDistributionLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(mainBasecallingSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mainBasecallingBrowseButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainSettingFilesPanelLayout.createSequentialGroup()
                        .addComponent(windowSizeForLengthDistributionLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainLdSettingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mainLdBrowseButton)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        mainSettingFilesPanelLayout.setVerticalGroup(
            mainSettingFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainSettingFilesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainSettingFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(windowSizeForLengthDistributionLabel1)
                    .addComponent(mainBasecallingSourceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainBasecallingBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainSettingFilesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(windowSizeForLengthDistributionLabel2)
                    .addComponent(mainLdSettingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainLdBrowseButton)))
        );

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxAgeOfPoresLabel)
                    .addComponent(totalNumberOfTicksLabel)
                    .addComponent(durPerTickLabel)
                    .addComponent(dimLabel)
                    .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nopLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                        .addComponent(sourceField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addGap(7, 7, 7)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(browseButton)
                            .addComponent(maxAgeOfPoresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOfTicksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(durationPerTickFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dimComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(mainSettingFilesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addComponent(numberOfPoresFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(windowSizeForLengthDistributionLabel)
                            .addComponent(outputFilenameLabel)
                            .addComponent(outputLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(outputFileTextField)
                            .addComponent(outputComboBox, 0, 85, Short.MAX_VALUE)
                            .addComponent(windowSizeFormattedTextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton)
                    .addComponent(outputFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputFilenameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nopLabel)
                    .addComponent(numberOfPoresFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputLabel)
                    .addComponent(outputComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(maxAgeOfPoresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maxAgeOfPoresLabel))
                    .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(windowSizeForLengthDistributionLabel)
                        .addComponent(windowSizeFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainSettingFilesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOfTicksTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalNumberOfTicksLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(durPerTickLabel)
                            .addComponent(durationPerTickFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dimComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dimLabel)))))
        );

        runPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Run"));

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.setEnabled(false);
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        pauseButton.setText("Pause");
        pauseButton.setEnabled(false);
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout runPanelLayout = new javax.swing.GroupLayout(runPanel);
        runPanel.setLayout(runPanelLayout);
        runPanelLayout.setHorizontalGroup(
            runPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(runPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pauseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        runPanelLayout.setVerticalGroup(
            runPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(runPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(runPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopButton)
                    .addComponent(pauseButton)
                    .addComponent(startButton))
                .addContainerGap())
        );

        outputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        outputScrollPane.setViewportView(outputTextArea);

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outputScrollPane)
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(outputScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        fileMenu.setText("File");

        loadFileMenuItem.setLabel("Load File");
        loadFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadFileMenuItem);

        exitMenuItem.setLabel("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        toolMenu.setText("Tools");

        createSettingFileMenuItem.setText("Create Settingfile");
        createSettingFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSettingFileMenuItemActionPerformed(evt);
            }
        });
        toolMenu.add(createSettingFileMenuItem);

        menuBar.add(toolMenu);

        settingsMenu.setText("Settings");

        InputSettingsMenuItem.setLabel("Input Settings");
        InputSettingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputSettingsMenuItemActionPerformed(evt);
            }
        });
        settingsMenu.add(InputSettingsMenuItem);

        menuBar.add(settingsMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(runPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(runPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>                        

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
    pauseButton.setEnabled(true);
    stopButton.setEnabled(true);

	String message= "<html>";
	Controller cd = null;
	int basecalling = 0;

	String chosen = (String) dimComboBox.getSelectedItem();

			if (chosen.equals("1D")) {
				//TODO
				basecalling =1;
			} else if (chosen.equals("2D")) {
			//TODO
				basecalling=2;
				}
			/* Tests for Gui Input
			System.out.println("Number of Pores: "+ Integer.parseInt(numberOfPoresFormattedTextField.getText()));
			System.out.println("Duration per Tick: "+ Integer.parseInt(durationPerTickFormattedTextField.getText()));
			System.out.println("Number of Ticks: "+Integer.parseInt(numberOfTicksTextField.getText()));
			System.out.println("Window Size: "+Integer.parseInt(windowSizeFormattedTextField.getText()));
			System.out.println("Basecalling: "+basecalling);
			System.out.println("Basecalling: "+basecalling);
			System.out.println("Input directory: "+sourceField.getText());
			System.out.println("Output: "+outputFileTextField.getText());
		*/
			/* 	
			private String inputFilename;
			private String outputFilename;
			private String writeInFileOption;
			private int basecalling;
			private int numberOfPores;
			private int maxAgeOfPores;
			private int durationOfTick;
			private int totalNumberOfTicks;
			private int windowSizeForLengthDistribution*/
			
		GUIOptions options = new GUIOptions(
				sourceField.getText(),
				outputFileTextField.getText(), 
				(String) outputComboBox.getSelectedItem(),
				basecalling, 
				Integer.parseInt(numberOfPoresFormattedTextField1.getText()),
				Integer.parseInt(maxAgeOfPoresTextField.getText()),
				Integer.parseInt(durationPerTickFormattedTextField.getText()),
				Integer.parseInt(numberOfTicksTextField.getText()),
				Integer.parseInt(windowSizeFormattedTextField.getText()));

		cd = new Controller(options);

		cd.run();
		
	


	int length= cd.getFastAErrors().size();

	for(int i=0; i<length;i++)
	{
		if(cd.getFastAErrors().get(i).isCriticalError()) {
			JOptionPane.showMessageDialog(null, cd.getFastAErrors().get(i).getErrorMessage(), "Critical Error", JOptionPane.ERROR_MESSAGE);
		} else {
			message= message + " " + cd.getFastAErrors().get(i).getErrorMessage()+"<br>";
		}
	}

	message=message+"</html>";

	outputTextArea.setText(message);  

    }                                           

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
    stopButton.setEnabled(false);
    }                                           

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                             
    System.exit(0);
    }                                            

    private void mainLdBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
    lengthDistributionChooser.showOpenDialog(minION.this);
    mainLdSettingTextField.setText(lengthDistributionChooser.getSelectedFile().getAbsolutePath());
    }                                                  

    private void mainBasecallingBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                            
    baseCallingChooser.showOpenDialog(minION.this);
    mainBasecallingSourceTextField.setText(baseCallingChooser.getSelectedFile().getAbsolutePath());
    }                                                           

    private void mainLdSettingTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void mainBasecallingSourceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        // TODO add your handling code here:
    }                                                              

    private void numberOfPoresFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                                                 
        // TODO add your handling code here:
    }                                                                

    private void durationPerTickFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                                  
        // TODO add your handling code here:
    }                                                                 

    private void maxAgeOfPoresTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void outputFileTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                    

    }                                                   

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        mainFileChooser.showOpenDialog(minION.this);
        sourceField.setText(mainFileChooser.getSelectedFile().getAbsolutePath());
          
    }                                            

    private void settingFileDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        settingFileDirectory.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        settingFileDirectory.showOpenDialog(minION.this);
        settingFileDirectoryTextField.setText(settingFileDirectory.getSelectedFile().getAbsolutePath());
    }                                                          

    private void settingFileDirectoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
    }                                                             

    private void bBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        createBasecallingBlastFileChooser.showOpenDialog(minION.this);
        bBlastPathTextField.setText(createBasecallingBlastFileChooser.getSelectedFile().getAbsolutePath());
    }                                             

    private void bBlastPathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void bNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void ldFastATextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void ldBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        createLengthDistributionFastAFileChooser.showOpenDialog(minION.this);
        ldFastATextField.setText(createLengthDistributionFastAFileChooser.getSelectedFile().getAbsolutePath());
    }                                              

    private void fastQActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void fastAActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void outputComboBoxActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void createSettingFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        optionsTabbedPane.setSelectedIndex(1);
        optionsDialog.setVisible(true);
    }                                                         

    private void loadFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void InputSettingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        optionsTabbedPane.setSelectedIndex(0);
        optionsDialog.setVisible(true);
    }                                                     

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
    pauseButton.setEnabled(false);
    stopButton.setEnabled(false);
    }                                          

 
    // Variables declaration - do not modify                     
    private javax.swing.JPanel InputPanel;
    private javax.swing.JMenuItem InputSettingsMenuItem;
    private javax.swing.JTextField bBlastPathTextField;
    private javax.swing.JLabel bBlastSourceFileLabel;
    private javax.swing.JButton bBrowseButton;
    private javax.swing.JComboBox bComboBox;
    private javax.swing.JButton bCreateButton;
    private javax.swing.JLabel bDimensionLabel;
    private javax.swing.JLabel bNameLabel;
    private javax.swing.JTextField bNameTextField;
    private javax.swing.JPanel basecallingPanel;
    private javax.swing.JButton browseButton;
    private javax.swing.JMenuItem createSettingFileMenuItem;
    private javax.swing.JComboBox dimComboBox;
    private javax.swing.JLabel dimLabel;
    private javax.swing.JLabel durPerTickLabel;
    private javax.swing.JFormattedTextField durationPerTickFormattedTextField;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JRadioButton fastA;
    private javax.swing.JRadioButton fastQ;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel inputFileType;
    private javax.swing.ButtonGroup inputFileTypeGroup;
    private javax.swing.JPanel inputTab;
    private javax.swing.JButton ldBrowseButton;
    private javax.swing.JButton ldCreateButton;
    private javax.swing.JLabel ldFastALabel;
    private javax.swing.JTextField ldFastATextField;
    private javax.swing.JTextField ldFileNameTextField;
    private javax.swing.JLabel ldNameLabel;
    private javax.swing.JPanel lengthDistributionPanel;
    private javax.swing.JMenuItem loadFileMenuItem;
    private javax.swing.JButton mainBasecallingBrowseButton;
    private javax.swing.JTextField mainBasecallingSourceTextField;
    private javax.swing.JButton mainLdBrowseButton;
    private javax.swing.JTextField mainLdSettingTextField;
    private javax.swing.JPanel mainSettingFilesPanel;
    private javax.swing.JLabel maxAgeOfPoresLabel;
    private javax.swing.JFormattedTextField maxAgeOfPoresTextField;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel nopLabel;
    private javax.swing.JFormattedTextField numberOfPoresFormattedTextField1;
    private javax.swing.JFormattedTextField numberOfTicksTextField;
    private javax.swing.JDialog optionsDialog;
    private javax.swing.JTabbedPane optionsTabbedPane;
    private javax.swing.JComboBox outputComboBox;
    private javax.swing.JTextField outputFileTextField;
    private javax.swing.JLabel outputFilenameLabel;
    private javax.swing.ButtonGroup outputGroup;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JScrollPane outputScrollPane;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JButton pauseButton;
    private javax.swing.JPanel runPanel;
    private javax.swing.JButton settingFileDirectoryButton;
    private javax.swing.JLabel settingFileDirectoryLabel;
    private javax.swing.JTextField settingFileDirectoryTextField;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JPanel settingsTab;
    private javax.swing.JTextField sourceField;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JMenu toolMenu;
    private javax.swing.JLabel totalNumberOfTicksLabel;
    private javax.swing.JLabel windowSizeForLengthDistributionLabel;
    private javax.swing.JLabel windowSizeForLengthDistributionLabel1;
    private javax.swing.JLabel windowSizeForLengthDistributionLabel2;
    private javax.swing.JFormattedTextField windowSizeFormattedTextField;
    // End of variables declaration                   

    public static void main(String[] args) {
        minION sim = new minION();
        sim.setVisible(true);
    }


}
